naming:
  FunctionNaming:
    ignoreAnnotated:
      - Composable

ktlint:
  code_style: android_studio
  TrailingCommaOnCallSite:
    useTrailingCommaOnCallSite: true
  TrailingCommaOnDeclarationSite:
    useTrailingCommaOnDeclarationSite: true
