name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Common setup
        uses: ./.github/actions/setup-android

      - name: Build
        run: ./gradlew buildDebug

  e2e-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Common setup
        uses: ./.github/actions/setup-android
        with:
          enable-kvm: true

      - name: Install Maestro
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      - name: Create debug APK
        run: ./gradlew assembleDebug

      - name: Run Maestro E2E Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 36
          target: google_apis
          arch: x86_64
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: |
            ./gradlew installDebug
            maestro test app/src/maestro/flows/main.yml

      - name: Archive Maestro test results on failure
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: maestro-test-results
          path: ~/.maestro/tests/*/
